version: "3"
services:
  nginx:
    image: registry.fit2cloud.com/public/nginx:1.27.0
    container_name: nginx
    volumes:
      - /tmp:/tmp
      #- /usr/local/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      #- /usr/local/nginx/conf/conf.d:/usr/local/nginx/conf/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-network
    restart: unless-stopped

networks:
  nginx-network: