version: "3"
services:
  nginx:
    image: registry.fit2cloud.com/public/nginx:1.27.0
    container_name: nginx
    volumes:
      #- /opt/nginx/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - /opt/nginx/conf/conf.d:/usr/local/nginx/conf/conf.d
      - /opt/nginx/ssl:/opt/nginx/ssl
      - /opt/nginx/logs:/usr/local/nginx/logs
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-network
    restart: unless-stopped

networks:
  nginx-network: